import { describe, expect, it } from "vitest";
import { stripProviderLeanHeader } from "./normalize-lean-source";

describe("stripProviderLeanHeader", () => {
  it("removes Aristotle-generated file preambles", () => {
    const source = `/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e49cdd64-07e5-4db1-995f-13a608c728a8

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

import Mathlib

theorem demo : True := by
  trivial`;

    expect(stripProviderLeanHeader(source)).toBe(`import Mathlib

theorem demo : True := by
  trivial`);
  });

  it("removes the header when wrapped in lean fences", () => {
    const source = `\`\`\`lean
/-
This file was generated by Aristotle.
-/
theorem demo : True := by
  trivial
\`\`\``;

    expect(stripProviderLeanHeader(source)).toBe(`theorem demo : True := by
  trivial`);
  });
});
