const LEAN_CODE_FENCE_RE = /^```(?:lean|lean4)?\s*|\s*```$/gim;
const IMPORT_MATHLIB_RE = /^\s*import\s+Mathlib\b/m;
const LEAN_HOLE_RE = /\b(?:sorry|admit)\b/;
const PROVIDER_HEADER_RE =
  /^[\uFEFF\s]*\/-\s*[\s\S]*?generated by Aristotle[\s\S]*?-\/\s*/i;

export function stripLeanCodeFences(source: string): string {
  return source.replace(LEAN_CODE_FENCE_RE, "").trim();
}

export function stripProviderLeanHeader(source: string): string {
  return stripLeanCodeFences(source).replace(PROVIDER_HEADER_RE, "").trim();
}

export function ensureMathlibImport(source: string): string {
  const normalized = stripProviderLeanHeader(source);

  if (IMPORT_MATHLIB_RE.test(normalized)) {
    return normalized;
  }

  return `import Mathlib\n\n${normalized}`;
}

export function containsLeanHoles(source: string): boolean {
  return LEAN_HOLE_RE.test(stripLeanCodeFences(source));
}
